import type { Metadata } from "next";

import "./globals.css";
import pkg from '#/package.json';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <meta name="version" content={pkg.version} />
      <link rel="stylesheet" href="https://cdn.baiwumm.com/fonts/MapleMono-CN-Regular/result.css" />
      <body>
        {children}
      </body>
    </html>
  );
}
